language: php

php:
- "7.3"

script:
- make
- make test

before_install:
  - wget -O phive.phar https://phar.io/releases/phive.phar
  - wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
  - gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/local/bin/phive
  - sudo apt-get install -y sassc
